[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.*"
reqwest = "0.12.*"
rust-embed = "8.3.*"

[[bin]]
name = "web-server"
path = "src/web-server.rs"

[[bin]]
name = "ddos-protection"
path = "src/ddos-protection.rs"
